default['spawnfcgi']['socket'] = '/var/run/php-fcgi.sock'
default['spawnfcgi']['owner'] = 'apache'
default['spawnfcgi']['group'] = 'apache'
default['spawnfcgi']['num'] = '32'
default['spawnfcgi']['pid'] = '/var/run/spawn-fcgi.pid'
